AWSTemplateFormatVersion: 2010-09-09
Description: deploy yaml files with aws cloudformation to create result S3 bucket to store data quality result.

Parameters:

  S3BucketNameSuffix:
    Type: String
    Description: Follows AWS Account ID to compose result S3 bucket name.
    Default: dataquality-report

Resources:
  ResultS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      BucketName: !Join
        - '-'
        - - !Ref AWS::AccountId
          - !Ref S3BucketNameSuffix
    DeletionPolicy: Retain