AWSTemplateFormatVersion: 2010-09-09
Description: create a glue job by aws cloudformation.


#!/usr/bin/env python3  
##--------------------------------------------------------------------
## File    :   s3validation.yaml
## Time    :   2022/12/05 12:02:01
## Author  :   Zheng Liu
## Version :   1.0
## Desc    :   deploy glue job to do glue catalog validation between lake formation database and S3 folders and save result in result S3 as well as sending out emails through SNS(created by glue-catalog-validation-1.yaml)

#---------------------------Version History---------------------------
#SrNo    DateModified    ModifiedBy   Description
#1       2022/12/05      Zheng        Initial Version
#2       2023/01/05      Zheng        Use S3 name as stack name, but change dot into two consecutive dashes

##--------------------------------------------------------------------


Parameters:
  gluejobfile:
    Type: String
    MinLength: '1'
    Description: path of the glue catalog validation glue job file
    Default: validationfile/glue-catalog-validation.py
    # Should saved in result S3 under folder of validationfile

  # GlueJobName:
  #   # stack naming rule: Stack name can include letters (A-Z and a-z), numbers (0-9), and dashes (-).
  #   # stackname should be <dish aws account name (replace dot with underscore)>---gluevalidation
  #   # example:
  #   # account name: aws-5g.dp.mss.data-science.dev
  #   # - = - (no need to change, this can be used in SNS, S3, CF Stack name and Glue Job name)
  #   # . = --
  #   # delimiter = ---
  #   # Demo target S3: s3-validation-demo
  #   # stackname: aws-5g--dp--mss--data-science--dev---s3-validation-demo

 
  GlueJobCommandName:
    Type: String
    MinLength: '1'
    Description: Name of the Glue Job command
    Default: glueetl

  GlueIAMRole:
    Type: String
    Description: Name of IAM role for Glue Job
    Default: GlueRoleSample
 
  GlueJobNumberOfWorkers:
    Type: Number
    Description: Number of the Glue Job workers
    Default: 149



Resources:

  TheGlueJob:
    Type: AWS::Glue::Job
    Properties: 
      Command: 
        Name: !Ref GlueJobCommandName
        ScriptLocation: !Join
          - ''
          - - 's3://'
            - !Select [0, !Split ["---", !Ref AWS::StackName]]
            - '---gluevalidation/'
            - !Ref gluejobfile
      Description: Triggered by S3 new object and do s3 validation and then output to SNS and S3
      GlueVersion: '3.0'
      MaxRetries: 0
      Name: !Ref AWS::StackName
      Role: !Ref GlueIAMRole
      Timeout: 300
      WorkerType: G.2X
      NumberOfWorkers: !Ref GlueJobNumberOfWorkers
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"