AWSTemplateFormatVersion: 2010-09-09
Description: create Glue Job, Glue Job role and SNS topic in an vendor account initially by aws cloudformation for glue-catalog-validation.

Parameters:
  AmazonS3FullAccessPolicy:
    Type: String
    Description: Need read and write from and to S3
    Default: arn:aws:iam::aws:policy/AmazonS3FullAccess

  AWSGlueServiceRolePolicy:
    Type: String
    Description: Saving execution record in logs
    Default: arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  AmazonSNSFullAccessPolicy:
    Type: String
    Description: Need to trigger SNS
    Default: arn:aws:iam::aws:policy/AmazonSNSFullAccess

  PermissionBoundary:
    Type: String
    MinLength: '1'
    Description: Permission boundary of the current role
    Default: TaaSAdminDev_Permission_Boundary

  SNSEndpoints:
    Type: String
    MinLength: '1'
    Description: Name of the subscriber of the SNS topic
    Default: metadq@dish.com

  SNSEndpointProtocol:
    Type: String
    MinLength: '1'
    Description: Name of the protocol to notice subscriber of the SNS topic
    Default: email

  Gluejobfile:
    Type: String
    MinLength: '1'
    Description: path of the glue catalog validation glue job file
    Default: glue_catalog_validation.py

  GlueJobCommandName:
    Type: String
    MinLength: '1'
    Description: Name of the Glue Job command
    Default: glueetl
 
  GlueJobNumberOfWorkers:
    Type: Number
    Description: Number of the Glue Job workers
    Default: 149

Resources:
  TheSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref SNSEndpoints
          Protocol: !Ref SNSEndpointProtocol
      TopicName: !Sub ${AWS::StackName}
      # SNS naming rule: Maximum 256 characters. Can include alphanumeric characters, hyphens (-) and underscores (_). FIFO topic names must end with ".fifo".
      
      # stack naming rule: Stack name can include letters (A-Z and a-z), numbers (0-9), and dashes (-).
      # stackname should be <dish aws account name (replace dot with underscore)>---gluevalidation
      # example:
      # account name: aws-5g.dp.mss.data-science.dev
      # - = - (no need to change, this can be used in SNS, S3, CF Stack name and Glue Job name)
      # . = --
      # delimiter = ---
      # stackname: aws-5g--dp--mss--data-science--dev---gluevalidation
      # SNS name: aws-5g--dp--mss--data-science--dev---gluevalidation
    DeletionPolicy: Delete

  TheGlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}GlueJobRole
      PermissionsBoundary: !Join 
        - ''
        - - "arn:aws:iam::"
          - !Ref "AWS::AccountId"
          - :policy/
          - !Ref PermissionBoundary     
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Ref AmazonS3FullAccessPolicy
        - !Ref AmazonSNSFullAccessPolicy
        - !Ref AWSGlueServiceRolePolicy

  TheGlueJob:
    Type: AWS::Glue::Job
    Properties: 
      Command: 
        Name: !Ref GlueJobCommandName
        ScriptLocation: !Join
          - ''
          - - 's3://'
            - !Join ['.', !Split ["--", !Select [0, !Split ["---", !Ref AWS::StackName]]]]
            - '/'
            - !Ref Gluejobfile
      Description: Computing Python code should be saved in the S3 top level
      GlueVersion: '3.0'
      MaxRetries: 0
      Name: !Ref AWS::StackName
      Role: !Ref TheGlueJobRole
      Timeout: 300
      WorkerType: G.2X
      NumberOfWorkers: !Ref GlueJobNumberOfWorkers
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"